proxy_env:
      https_proxy: https://proxy:8888
deployment_dir: /opt/epicsTest
epics_base_version: R7.0.3.1
synApps_version: R6-1
epics_modules: 
      - ipac
      - asyn
      - autosave  
# We need to have a list and an array 
# to be able to loop over two variables in the git module
epicsmodules:
  ipac: 
    version: 2.15
  asyn:
    version: R4-37
  autosave:
    version: R5-10  

        