---
- name: Deploy AreaDetector on a target host
  hosts: all
  become: true
  vars:
        deployment_dir: /opt/epicsTest
        epics_base_version: R7.0.3.1
  tasks:
      - include_role:
          name: CentOS
        when: ansible_os_family == 'RedHat'
        
      - include_role:
          name: Debian
        when: ansible_os_family == 'Debian'
      - include_vars: config.yml
      - name: clone epic_base 
        git:
              clone: yes
              update: yes
              recursive: yes
              track_submodules: yes
              force: yes
              dest: "{{deployment_dir}}/epics-base"
              repo: https://github.com/epics-base/epics-base
              version: "R7.0.3.1"
        environment:
            https_proxy: https://proxy:8888

      - name: buid base Later will build all, just like install all packages
        command: 
              cmd: make -sj
              chdir: "{{deployment_dir}}/epics-base" 
            