---
- name: Deploy AreaDetector on a target host
  hosts: all
  become: true
  vars:     
    synApps_modules: 
      - configure
      - documentation
      - utils
    
  tasks:
      - name: include vars 
        include_vars: config.yml
      # install necessary libraries depending on the OS 
      # we are deploying on
      - include_role:
          name: CentOS
        when: ansible_os_family == 'RedHat'
        
      - include_role:
          name: Debian
        when: ansible_os_family == 'Debian'
      
      - include_role:
          name: clone
                      
     

      - name: clone "{{epics_modules}}"  
        git:
              clone: yes
              update: yes
              force: yes
              dest: "{{deployment_dir}}/support/{{ item }}"
              repo: "https://github.com/epics-modules/{{ item }}"
              #version: "{{ ipac.version }}"
              version: "{{ epicsmodules[item].version }}"
        with_items:  
          - "{{ epics_modules }}"   
        environment: 
             https_proxy: https://proxy:8888      

#      - name: buid base Later will build all, just like install all packages
#        command: 
#              cmd: make -sj
#              chdir: "{{deployment_dir}}/epics-base" 
#            