# - name: The following {{packages}} is installed
# # Install specific packages for ADEiger
#   yum:
#     name: "{{ packages }}"
#     state: present
#   vars: 
#     packages:
#          - zeromq-devel
#   when:  "ansible_os_family == 'RedHat'"      

# - name: The following {{ packages }} is installed
#   apt:
#       name: "{{ packages }}"
#       state: present
#   vars: 
#       packages:
#                   - libzmq5-dev
#       forse_apt_get: yes
#   when:  "ansible_os_family == 'Debian'"      
- name: clone ADProsilica
  git: 
        clone: yes
        update: yes
        force: yes
        dest: "{{deployment_dir}}/support/areaDetector/ADProsilica"
        repo: "https://github.com/areaDetector/ADProsilica"
        version: "{{_AD_modules_local.ADProsilica.version }}"
  environment: "{{ proxy_https }}" 

- name: build ADProsilica
  command: 
  args: 
        cmd: make -sj
        chdir: "{{deployment_dir}}/support/areaDetector/ADProsilica"
