- name: clone epic_base        
  git:
        clone: yes
        update: yes
        recursive: yes
        track_submodules: yes
        force: yes
        dest: "{{deployment_dir}}/epics-base"
        repo: https://github.com/epics-base/epics-base
        version: "{{epics_base_version}}"
  environment: "{{ proxy_env }}"
- name: clone synApps  into support       
  git:
        clone: yes
        update: yes
        recursive: yes
        track_submodules: yes
        force: yes
        dest: "{{deployment_dir}}/support"
        repo: https://github.com/EPICS-synApps/support
        version: "{{synApps_version}}"
  environment: "{{ proxy_env }}"

- name: clone synApps modules [configure, documentation, utils]  
  git:
        clone: yes
        update: yes
        force: yes
        dest: "{{deployment_dir}}/support/{{ item }}"
        repo: "https://github.com/EPICS-synApps/{{ item }}"
        version: "{{synApps_version}}"
  with_items:  
    - "{{ synApps_modules }}"     
  environment: "{{ proxy_env }}"    

- name: clone "{{epics_modules}}"  
  git:
        clone: yes
        update: yes
        force: yes
        dest: "{{deployment_dir}}/support/{{ item }}"
        repo: "https://github.com/epics-modules/{{ item }}"
        #version: "{{ ipac.version }}"
        version: "{{ epicsmodules[item].version }}"
  with_items:  
    - "{{ epics_modules }}"   
  environment: "{{ proxy_env }}"
   
